### ISSUE TITLE
Ad templates - Updated Request

### ISSUE THREAD

**Issue by cwiklata** [dig-eg-gaz/advertisements#14]
I'm missing a large amount of templates still:

For page 2:
G G Drossos
Au de Rogue
John B Caffari Pilsener drink image
Lipton Limited
Grand Hotel Khartoum
Cairo Mena House Hotel
Shepheard's Hotel
Grand Continental Hotel
Upper Egypt Hotels Co
Cairo Photographic Stores
Notice - I think I need a template because it looks more like an ad than a block of text
French image with ad
Calvert's Carbolic Tooth Powder
Grand Hotel National 
Egyptian Gazette Subscription

For pg.3:
American Stocks and sales chart
Isherwood's Cairo cigarettes
Maeris Hotel
Eden Palace Hotel
Betlitz School of Language
Anglo-American Stores

Pg 5:
A&M Samuelson Bros
Kupper's bier in siphones (German and different format)
Rose's Lime Juice

I am missing loads for page 6 but they're mostly hotels and I imagine they'll eventually be uploaded as templates

**Comment by whanley** [comment]
@cwiklata thanks aplenty. I need you to upload your image files to the page-images repository to finish this process. Can you check with me about this on Wednesday?

**Comment by whanley** [comment]
- [x] G G Drossos
- [x] Au de Rogue
- [x] John B Caffari Pilsener drink image
- [x] Lipton Limited
- [x] Grand Hotel Khartoum
- [x] Cairo Mena House Hotel
- [x] Shepheard's Hotel
- [x] Grand Continental Hotel
- [x] Upper Egypt Hotels Co
- [x] Cairo Photographic Stores
- [x] Notice - No template needed because it's a single ad.
- [x] French image with ad
- [x] Calvert's Carbolic Tooth Powder
- [x] Grand Hotel National
- [x] Egyptian Gazette Subscription

- [x] American Stocks and sales chart
- [x] Isherwood's Cairo cigarettes
- [x] Maeris Hotel
- [x] Eden Palace Hotel
- [x] Betlitz School of Language
- [x] Anglo-American Stores

- [x] A&M Samuelson Bros
- [x] Kupper's bier in siphones (German and different format)
- [x] Rose's Lime Juice
